<!DOCTYPE html>
<html>
<head>
	<title>Users</title>
	<link rel="stylesheet" type="text/css" href="css/users.css">

	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="js/users.js"></script>
</head>
<body>
	<div id="usersTableDiv">
		<table id="users">
			<thead>
				<tr>
					<th>First name</th>
					<th>Last name</th>
					<th>Email</th>
					<th>Mobile</th>
					<th>Password</th>
					<th>Edit user</th>
					<th><a href="/zend.local/public/users/add">Add user</a></th>
				</tr>
			</thead>
			<tbody>
				<?php
					foreach ($this->users as $user):
				?>
				<tr>
					<td><?php echo $user["firstname"]; ?></td>
					<td><?php echo $user["lastname"]; ?></td>
					<td><?php echo $user["email"]; ?></td>
					<td><?php echo $user["mobile"]; ?></td>
					<td><?php echo $user["password"]; ?></td>
					<td><button class="editUserBtn edit" data-userId="<?php echo 'user-' . $user["user_id"]?>">Edit</button></td>
				</tr>

				<?php endforeach;?>
			</tbody>
		</table>
	</div>


</body>
</html>